#!/bin/bash
echo "Script de teste para webhooks - 1"
NUMBER=$(($NUMBERONE + $NUMBERTWO))
echo "$NUMBER"
echo "Isso vai ser adicionado de verdade."
echo "ADICIONADO, TESTANDO 2"
echo "ADICIONADO, TESTANDO 3"
echo "ADICIONADO, TESTANDO 4"
echo "ADICIONADO, TESTANDO 5"
echo "ADICIONADO, TESTANDO 9..MAIS TESTES"
echo "ADICIONADO, TESTANDO 10..MAIS TESTES AINDA"
echo "ADICIONADO, AINDA TESTANDO 12..MAIS TESTES AINDA"
echo "QUALQUER TEXTO"
